[package]
name="qa-engine"
version.workspace=true
edition.workspace=true
license.workspace=true
[dependencies]
qa-model={path="../qa-model",version="=0.1.0"}
qa-policy={path="../qa-policy",version="=0.1.0"}
qa-syntax={path="../qa-syntax",version="=0.1.0"}
qa-rules={path="../qa-rules",version="=0.1.0"}
qa-backends={path="../qa-backends",version="=0.1.0"}

[dev-dependencies]
serde_json.workspace=true
