use qa_model::{EvidenceKind, RuleDefinition, RuleRegistry};

pub fn rule_registry() -> RuleRegistry {
    let static_rules = &[
        ("QA-SPRAWL-001", "File line limit", "SPRAWL"),
        ("QA-SPRAWL-002", "Function body length", "SPRAWL"),
        ("QA-SPRAWL-003", "Parameter/generic sprawl", "SPRAWL"),
        ("QA-SPRAWL-004", "Type bloat", "SPRAWL"),
        ("QA-METRIC-001", "Cyclomatic complexity", "METRIC"),
        ("QA-METRIC-002", "Cognitive complexity", "METRIC"),
        ("QA-DUP-002", "Structural duplicate", "DUP"),
        ("QA-DEAD-001", "Unreachable internal item", "DEAD"),
        ("QA-DEAD-002", "Unreferenced exported API", "DEAD"),
        ("QA-ARCH-001", "Layer violation", "ARCH"),
        ("QA-TEST-001", "Assertionless test", "TEST"),
        ("QA-TEST-002", "Tautological assertion", "TEST"),
        ("QA-TEST-003", "No production reachability", "TEST"),
        ("QA-TEST-005", "Nondeterministic test", "TEST"),
        ("QA-FUZZ-001", "Critical parser fuzz target", "FUZZ"),
        ("QA-FUZZ-004", "Vacuous fuzz target", "FUZZ"),
        ("QA-SAFE-001", "Production unwrap", "SAFE"),
        ("QA-SAFE-002", "Production expect", "SAFE"),
        ("QA-SAFE-003", "Production panic", "SAFE"),
        ("QA-MATH-001", "Explicit arithmetic semantics", "MATH"),
        ("QA-PARSE-002", "Unbounded parser read", "PARSE"),
        ("QA-RES-001", "Unbounded channel", "RES"),
        ("QA-ALLOC-001", "Explicit leak primitive", "ALLOC"),
        ("QA-ENV-002", "Hardcoded host path", "ENV"),
        ("QA-STATE-001", "Transition completeness", "STATE"),
        ("QA-STATE-002", "State serialization round-trip", "STATE"),
        ("QA-STATE-003", "Unreachable state", "STATE"),
        ("QA-STATE-004", "Illegal transition rejection", "STATE"),
        ("QA-STATE-005", "Terminal invariant", "STATE"),
        ("QA-STATE-006", "Restart/persistence invariant", "STATE"),
        ("QA-STATE-007", "Transition atomicity", "STATE"),
        ("QA-ASYNC-001", "Cancellation contract", "ASYNC"),
        ("QA-ASYNC-002", "Panic in Drop", "ASYNC"),
        ("QA-ASYNC-003", "Blocking async call", "ASYNC"),
        ("QA-ASYNC-004", "Detached task", "ASYNC"),
        ("QA-ASYNC-005", "Lock across await", "ASYNC"),
        ("QA-CONC-003", "Unsafe Send/Sync", "CONC"),
        ("QA-CONC-004", "Shared mutable static", "CONC"),
        ("QA-CONC-006", "Atomic ordering policy", "CONC"),
        ("QA-ERR-001", "Discarded result", "ERR"),
        ("QA-ERR-002", "Sensitive formatting/logging", "ERR"),
        ("QA-ERR-003", "Broken error source chain", "ERR"),
        ("QA-ERR-004", "Lost error context", "ERR"),
        ("QA-SECRET-002", "Zeroize contract", "SECRET"),
        ("QA-CT-001", "Secret branch", "CT"),
        ("QA-CT-002", "Secret index", "CT"),
        ("QA-BUILD-002", "Writes outside OUT_DIR", "BUILD"),
        ("QA-BUILD-003", "Build network", "BUILD"),
        ("QA-BUILD-004", "Build process spawn", "BUILD"),
        ("QA-BUILD-006", "Build rerun contract", "BUILD"),
        ("QA-BUILD-007", "Proc-macro network", "BUILD"),
        ("QA-BUILD-008", "Proc-macro process spawn", "BUILD"),
        ("QA-BUILD-009", "Proc-macro environment dependency", "BUILD"),
        ("QA-LAYOUT-001", "Explicit layout", "LAYOUT"),
        ("QA-LAYOUT-006", "Raw padded byte cast", "LAYOUT"),
        ("QA-LAYOUT-008", "Packed reference/alignment audit", "LAYOUT"),
        ("QA-FFI-001", "ABI-stable FFI types", "FFI"),
        ("QA-FFI-002", "FFI panic boundary", "FFI"),
        ("QA-FFI-003", "FFI safety docs", "FFI"),
        ("QA-FFI-004", "Raw-pointer safety contract", "FFI"),
        ("QA-HW-001", "Volatile MMIO access", "HW"),
        ("QA-HW-002", "Interrupt stack budget", "HW"),
        ("QA-HW-003", "Linker symbol contract", "HW"),
        ("QA-HW-004", "Interrupt operation safety", "HW"),
        ("QA-HW-006", "DMA contract", "HW"),
        ("QA-PERF-001", "False-sharing hazard", "PERF"),
        ("QA-PERF-002", "Vectorization contract", "PERF"),
        ("QA-PERF-005", "Hot-path hygiene", "PERF"),
        ("QA-HARDEN-001", "Release overflow checks", "HARDEN"),
        ("QA-SNAP-001", "Snapshot auto-approval", "SNAP"),
        ("QA-SNAP-003", "Pending snapshot", "SNAP"),
        ("QA-SNAP-005", "Snapshot secret leakage", "SNAP"),
        ("QA-DOC-001", "Public API documentation", "DOC"),
        ("QA-DOC-002", "Critical API example", "DOC"),
        ("QA-DEP-003", "Forbidden dependency source", "DEP"),
        ("QA-DEP-004", "Wildcard dependency version", "DEP"),
        ("QA-API-003", "Internal type leakage", "API"),
        ("QA-API-005", "Unsafe API safety contract", "API"),
        ("QA-API-006", "Result API must-use contract", "API"),
        ("QA-EXC-001", "Expired exception", "EXC"),
        ("QA-EXC-002", "Missing exception reason", "EXC"),
    ];
    let compiler_rules = &[
        ("QA-COV-001", "Coverage threshold", "COV"),
        ("QA-COV-002", "Coverage unavailable", "COV"),
        ("QA-METRIC-004", "CRAP score", "METRIC"),
        ("QA-MIR-001", "Drop cleanup", "MIR"),
        ("QA-MIR-002", "Zeroization survival", "MIR"),
        ("QA-MIR-003", "Panic edges", "MIR"),
        ("QA-MIR-004", "No-allocation contract", "MIR"),
        ("QA-MIR-005", "Async state retention", "MIR"),
        ("QA-CFG-001", "Default features", "CFG"),
        ("QA-CFG-002", "No-default features", "CFG"),
        ("QA-CFG-003", "All features", "CFG"),
        ("QA-CFG-004", "Each-feature matrix", "CFG"),
        ("QA-CFG-020", "MSRV", "CFG"),
    ];
    let dynamic_rules = &[
        ("QA-MUT-001", "Mutation threshold", "MUT"),
        ("QA-MUT-002", "Surviving mutant", "MUT"),
        ("QA-MUT-003", "Timed-out mutant", "MUT"),
        ("QA-FUZZ-005", "Fuzz target build", "FUZZ"),
        ("QA-SAN-001", "Address/leak sanitizer", "SAN"),
        ("QA-SAN-002", "Thread sanitizer", "SAN"),
        ("QA-SAN-003", "Memory sanitizer", "SAN"),
        ("QA-SAN-005", "Sanitizer matrix", "SAN"),
        ("QA-DIFF-001", "Legacy equivalence", "DIFF"),
        ("QA-DIFF-002", "Reference equivalence", "DIFF"),
        ("QA-DIFF-004", "Oracle independence", "DIFF"),
        ("QA-DIFF-005", "Divergence persistence", "DIFF"),
        ("QA-FAULT-001", "I/O/allocation failure", "FAULT"),
        ("QA-FAULT-002", "Clock/latency skew", "FAULT"),
        ("QA-FAULT-003", "Partial I/O", "FAULT"),
        ("QA-FAULT-007", "Replayability", "FAULT"),
        ("QA-HW-005", "MMIO width/alignment evidence", "HW"),
        ("QA-PERF-003", "Instruction/codegen drift execution", "PERF"),
        ("QA-BLOAT-001", "Binary bloat execution", "BLOAT"),
        ("QA-BLOAT-010", "LLVM/codegen bloat execution", "BLOAT"),
        ("QA-HARDEN-002", "Final artifact mitigation execution", "HARDEN"),
        ("QA-SNAP-002", "Orphan snapshot execution", "SNAP"),
        ("QA-DOC-003", "Doctest execution", "DOC"),
        ("QA-DEP-001", "cargo-deny execution", "DEP"),
        ("QA-DEP-002", "Unused dependency execution", "DEP"),
        ("QA-API-004", "SemVer execution", "API"),
        ("QA-GEN-001", "Generator reproduction execution", "GEN"),
        ("QA-GEN-002", "Generator determinism", "GEN"),
        ("QA-REPRO-001", "Reproducible build execution", "REPRO"),
    ];
    let mut rules = Vec::new();
    rules.extend(build(static_rules, EvidenceKind::Static));
    rules.extend(build(compiler_rules, EvidenceKind::Compiler));
    rules.extend(build(dynamic_rules, EvidenceKind::Dynamic));
    RuleRegistry { rules }
}
fn build(rows: &[(&str, &str, &str)], kind: EvidenceKind) -> Vec<RuleDefinition> {
    rows.iter()
        .map(|(id, name, family)| RuleDefinition {
            id: (*id).into(),
            name: (*name).into(),
            family: (*family).into(),
            evidence: kind,
            description: (*name).into(),
        })
        .collect()
}
